# Config for writing documentation

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

conda:
  file: environment.yml

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: extra_requirements/requirements-tests.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .

formats:
  - pdf
  - epub
