# Config for writing documentation

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-4.7"

sphinx:
  configuration: docs/source/conf.py

conda:
  file: docs/environment.yml

python:
  install:
    - requirements: extra_requirements/requirements-tests.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .

formats:
  - pdf
  - epub
