# Setup file for read the docs for python 3.8
# See https://readthedocs.org/projects/docs/downloads/pdf/stable/
version: 2

build:
  os: "ubuntu-18.04"
  tools:
    python: "3.7"

sphinx:
  configuration: docs/source/conf.py

python:
  # Install our python package before building the docs
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .

formats:
  - pdf
  - epub
