# Config for writing documentation

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-20.04  # <- add this line
  tools:
    python: "3.8"


python:
  version: "3.8"
  install:
    - requirements: extra_requirements/requirements-tests.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .

formats:
  - pdf
  - epub
