name: Test package

# Trigger this code when a new release is published
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
  push:
    branches:
      - master
      - stable

jobs:
  update:
    name: "${{ matrix.test }}_py${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        python-version: [3.7, 3.8, 3.9]
        test: ['coveralls', 'pytest']
        # Only run coverage / no_database on py3.8
        exclude:
          - python-version: 3.7
            test: coveralls
          - python-version: 3.9
            test: coveralls
    steps:
      # Setup and installation
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'extra_requirements/requirements-tests.txt'
      - name: Install requirements
        run: pip install -r extra_requirements/requirements-tests.txt
      - name: Test package
        # This is running a normal test
        if: matrix.test == 'pytest'
        env:
          ALLOW_WFSIM_TEST: 1
          TEST_MONGO_URI:  'mongodb://localhost:27017/'
        run: |
          pytest -rsxv --durations 0
      - name: Coveralls
        # Make the coverage report and upload
        env:
          NUMBA_DISABLE_JIT: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.test == 'coveralls'
        run: |
          coverage run --source=amstrax setup.py test -v
          coveralls --service=github
      # Done
      - name: goodbye
        run: echo "tests done, bye bye"
